### ISSUE TITLE
Accessibility client-side insights do not work on some sites

### ISSUE THREAD

**Issue by JakeChampion** [ftlabs/perf-widget#104]
ebay.co.uk and jakechampion.name do not have the accessibility insight due to a JS error.

```
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'. TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at TypeError (native)
    at getBackgroundColorForEl (chrome-extension://gdcpkokneogmbhggcgccfambkjinmhak/scripts/main.js:83:22)
    at getBackgroundColorForEl (chrome-extension://gdcpkokneogmbhggcgccfambkjinmhak/scripts/main.js:87:11)
    at getBackgroundColorForEl (chrome-extension://gdcpkokneogmbhggcgccfambkjinmhak/scripts/main.js:87:11)
    at getBackgroundColorForEl (chrome-extension://gdcpkokneogmbhggcgccfambkjinmhak/scripts/main.js:87:11)
    at getBackgroundColorForEl (chrome-extension://gdcpkokneogmbhggcgccfambkjinmhak/scripts/main.js:87:11)
    at getContrastForEl (chrome-extension://gdcpkokneogmbhggcgccfambkjinmhak/scripts/main.js:96:27)
    at textNodes.forEach.inNode (chrome-extension://gdcpkokneogmbhggcgccfambkjinmhak/scripts/main.js:115:18)
    at Array.forEach (native)
    at generateContrastData (chrome-extension://gdcpkokneogmbhggcgccfambkjinmhak/scripts/main.js:113:13)
```

**Comment by AdaRoseCannon** [comment]
I'm on it.
